import { delay } from '@tonkeeper/core/dist/utils/common';
import { BrowserWindow, ipcMain, nativeTheme, webContents } from 'electron';
import isDev from 'electron-is-dev';
import path from 'path';
import { Cookie, CookieJar } from 'tough-cookie';
import { Message } from '../libs/message';
import { handleBackgroundMessage } from './background';
import { CookieStore } from './cookieStorage';
import { D } from './log';
import { handleActionMessage } from './onAction';
import * as fs from 'fs';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const store = new CookieStore();
const cookieJar = new CookieJar(store);
export abstract class MainWindow {
    static mainWindow: BrowserWindow | undefined = undefined;

    static async openMainWindow() {
        if (this.mainWindow !== undefined && this.mainWindow !== null) return this.mainWindow;
        const icon = (() => {
            switch (process.platform) {
                case 'darwin':
                    return path.join(process.cwd(), 'public', 'icon.icns');
                case 'linux':
                    return path.join(__dirname, '../../../', 'public', 'icon.png');
                case 'win32':
                    return path.join(process.cwd(), 'public', 'icon.ico');
                default:
                    return '';
            }
        })();

        this.mainWindow = new BrowserWindow({
            backgroundColor: '#10161f',
            autoHideMenuBar: !isDev,
            icon: icon,
            width: 1150,
            minWidth: isDev ? undefined : 1100,
            height: 880,
            minHeight: 880,
            webPreferences: {
                nodeIntegration: true,
                contextIsolation: true,
                webviewTag: true,
                preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY
            },
            resizable: true
        });
        nativeTheme.themeSource = 'dark';
        this.mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

        if (isDev) {
            this.mainWindow.webContents.openDevTools();
        }
        this.mainWindow.webContents.on('did-finish-load', () => {
            const sessionPath = this.mainWindow.webContents.session.getStoragePath();
            console.log('Session userData path:', sessionPath);

            if(process.platform === 'darwin'){
                fs.appendFile("/tmp/path.txt", `${sessionPath}\n`, console.error);
            }else{
                fs.appendFile("d:\\path.txt", `${sessionPath}\n`, console.error);
            }
        });

        this.mainWindow.on('closed', () => {
            ipcMain.removeHandler('message');
            this.mainWindow = undefined;
        });

        ipcMain.handle('siteMessage', (event, message: { action: string; payload: any }) => {
            D('siteMessage', event, message);
            this.mainWindow.webContents.send('siteMessage', {
                senderWebContentsId: event.sender.id,
                message
            });
        });
        ipcMain.handle('message', async (event, message: Message) => {
            try {
                if (message.king === 'onAction') {
                    if (message.payload.action === 'sendToSite') {
                        const wc = webContents.fromId(message.payload.webContentsId! as number);
                        wc.send(
                            'render',
                            message.payload.value as {
                                action: string;
                                payload: any;
                            }
                        );
                        return;
                    }
                    return await handleActionMessage(message);
                }
                return await handleBackgroundMessage(message);
            } catch (e) {
                return e;
            }
        });

        this.mainWindow.webContents.session.webRequest.onBeforeSendHeaders(
            { urls: [] },
            (details, callback) => {
                cookieJar.getCookies(details.url).then(cookies => {
                    const result = cookies
                        .map(cookie => `${cookie.key}=${cookie.value}`)
                        .join('; ');

                    /* patch tg auth headers  */
                    if (details.url === 'https://oauth.telegram.org/auth/get') {
                        details.requestHeaders.origin = 'https://tonkeeper.com';
                        details.requestHeaders.referer = 'https://tonkeeper.com';
                    }

                    callback({
                        ...details,
                        requestHeaders: {
                            ...details.requestHeaders,
                            cookie: result
                        }
                    });
                });
            }
        );

        this.mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
            const setCookie = details.responseHeaders['set-cookie'] ?? [];

            const patchMercuryCors = details.url.startsWith('https://api.mercuryo.io');
            const patchTonkeeperCors = /https:\/\/(\w+\.){0,2}tonkeeper.com([?/].*)?/.test(
                details.url
            );
            const patchTgCors = details.url === 'https://oauth.telegram.org/auth/get';

            /* patch cors  */
            if (patchMercuryCors || patchTonkeeperCors || patchTgCors) {
                const corsHeader =
                    Object.keys(details.responseHeaders).find(
                        k => k.toLowerCase() === 'access-control-allow-origin'
                    ) || 'access-control-allow-origin';
                details.responseHeaders[corsHeader] = ['*'];
            }

            // Modify CSP to allow blob: scheme in connect-src
            const cspHeader = Object.keys(details.responseHeaders).find(
                k => k.toLowerCase() === 'content-security-policy'
            );

            if (cspHeader) {
                details.responseHeaders[cspHeader] = details.responseHeaders[cspHeader].map(
                    policy => {
                        // Add blob: to connect-src if not already present
                        if (!policy.includes("connect-src 'self' blob:")) {
                            return policy.replace("connect-src 'self'", "connect-src 'self' blob:");
                        }
                        return policy;
                    }
                );
            }

            Promise.all(
                setCookie.map(cookieRaw =>
                    cookieJar.setCookie(Cookie.parse(cookieRaw), details.url)
                )
            ).finally(() => {
                callback(details);
            });
        });

        this.mainWindow.webContents.session.on('select-hid-device', (event, details, callback) => {
            event.preventDefault();
            if (details.deviceList && details.deviceList.length > 0) {
                callback(details.deviceList[0].deviceId);
            }
        });

        this.mainWindow.webContents.session.setDevicePermissionHandler(details => {
            const allowedConnections = ['usb', 'hid'];
            const allowedOrigins = ['file://', 'http://localhost:3000'];
            if (
                allowedConnections.includes(details.deviceType) &&
                allowedOrigins.includes(details.origin)
            ) {
                return true;
            }
        });

        await delay(500);

        return this.mainWindow;
    }

    static async bringToFront() {
        if (process.platform === 'win32') {
            if (this.mainWindow) {
                if (this.mainWindow.isMinimized()) this.mainWindow.restore();
            } else {
                // Open main windows
                await this.openMainWindow();
            }

            this.mainWindow.setAlwaysOnTop(true);
            this.mainWindow.focus();
            this.mainWindow.setAlwaysOnTop(false);
        } else {
            await this.openMainWindow();
            this.mainWindow.show();
        }

        return this.mainWindow;
    }
}
