name: Web3ExplorerBeta CD
on:
    pull_request:
        branches:
            - main
            - feature
env:
    node-version: 20.11.1

permissions:
    contents: write

jobs:
    desktop-build:
        name: pull-request-test
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      tag: x64
                      command: make:x64
        runs-on: ${{ matrix.os }}
        timeout-minutes: 30
        env:
            VERSION: 1.0.53
            PROJECT_NAME: Web3ExplorerBeta
            APPLE_API_KEY: ${{ github.workspace }}/AuthKey.p8
            APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
            APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
            GITHUB_REPOSITORY: ${{ github.repository }}
            MAKE_OUT_DIR: ${{ github.workspace }}/apps/desktop/out/make
            GH_TOKEN: ${{ github.token }}
        steps:
            - name: Checkout to git repository
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.node-version }}
            - name: Enable Corepack
              run: |
                  corepack enable

            - name: Decode p8 base64 to a file
              if: runner.os == 'macOS'
              env:
                  CREDENTIALS: ${{ secrets.APPLE_API_KEY_B64 }}
              run: |
                  echo $CREDENTIALS | base64 -d > ${{ github.workspace }}/AuthKey.p8
            - name: Configure keychain
              if: runner.os == 'macOS'
              uses: apple-actions/import-codesign-certs@v3
              with:
                  p12-file-base64: ${{ secrets.IDENTITY_P12_B64 }}
                  p12-password: ${{ secrets.IDENTITY_PASSPHRASE }}

            - name: Run install
              uses: borales/actions-yarn@v5
              with:
                  cmd: install
            - name: Build Pkg
              run: |
                  cd ${{ github.workspace }}
                  yarn workspace @tonkeeper/locales build:rm
                  yarn build:pkg
                  echo "export { App } from '@web3-explorer/app/dist/src/desktop/App';" > apps/desktop/src/app/App.tsx
